In [1]:
import numpy as np

In [2]:
# first method
arr_1 = np.array([2,3,5,8,3,5,8,1])

In [3]:
arr_1

array([2, 3, 5, 8, 3, 5, 8, 1])

In [6]:
# second method
# arr_2 = np.arange(1,10)
arr_2 = np.arange(1,51,5)

In [7]:
arr_2

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [12]:
# third method
# it will return 50 elements with equal difference
np.linspace(1,100,num=20,retstep=True)

(array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526,  27.05263158,  32.26315789,  37.47368421,
         42.68421053,  47.89473684,  53.10526316,  58.31578947,
         63.52631579,  68.73684211,  73.94736842,  79.15789474,
         84.36842105,  89.57894737,  94.78947368, 100.        ]),
 5.2105263157894735)

In [14]:
# fourth method
# np.zeros(5)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
x = np.array([[4,5,6],[2,3,6],[1,7,7]])

In [19]:
x

array([[4, 5, 6],
       [2, 3, 6],
       [1, 7, 7]])

In [20]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
np.random.random()

0.0154844204946607

In [31]:
np.random.rand()

0.9856509304299697

In [33]:
# fifth method
np.random.random([3,3])

array([[0.23946942, 0.9886706 , 0.45822454],
       [0.33488728, 0.38590988, 0.27240044],
       [0.45080651, 0.65012313, 0.70809364]])

In [36]:
np.random.rand(3,3)

array([[0.48892348, 0.1504452 , 0.59321041],
       [0.45045867, 0.01041881, 0.03079901],
       [0.12190703, 0.58460303, 0.70919146]])

In [37]:
np.random.randn(3,3)

array([[ 0.24242371,  0.27891419, -1.06325436],
       [-0.36800802, -0.55276244, -2.11880758],
       [ 0.27468305, -2.31819918, -1.64833596]])

In [41]:
# sixth method
np.random.randint(10,20,7)

array([15, 16, 14, 19, 12, 10, 15])

In [42]:
np.random.randint(1,100,(4,4))

array([[93, 48, 36,  9],
       [19, 21, 62,  8],
       [18, 16, 63, 62],
       [88, 14, 92, 25]])

In [43]:
x = np.random.randint(1,100,(4,4))

In [48]:
x

array([[16, 56, 53, 55],
       [57, 64, 87, 67],
       [72,  8, 38, 77],
       [97, 94,  5, 19]])

In [45]:
x[0]

array([16, 56, 53, 55])

In [46]:
x[1]

array([57, 64, 87, 67])

In [47]:
x[0][1]

56

In [49]:
x[0:2]

array([[16, 56, 53, 55],
       [57, 64, 87, 67]])

In [50]:
x[:,0:2]

array([[16, 56],
       [57, 64],
       [72,  8],
       [97, 94]])

In [51]:
x[0:2,0:2]

array([[16, 56],
       [57, 64]])

In [64]:
np.random.seed(10)
x = np.random.randint(10,200,20)

In [65]:
x

array([ 19, 135,  25,  74, 123, 133, 166, 167, 123,  18,  83,  10,  50,
       174, 125,  26, 110, 149,  64,  98])

In [66]:
np.ndim(x)

1

In [67]:
x.shape

(20,)

In [68]:
x.max()

174

In [69]:
x.min()

10

In [70]:
# index at which max value is present
x.argmax()

13

In [71]:
# index at which min value is present
x.argmin()

11